### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Lee0701** [Lee0701/HeonOt#1]
앞으로 할 일 목록입니다.

- [x] 이벤트 처리 라이브러리 도입

- [x] DefaultSoftKeyboard의 설정 항목 추가

- [x] UnicodeCharacterGenerator에 두벌식 입력 (도깨비불) 구현

- [x] 낱자 조합 테이블 설정 항목 추가

- [ ] 설정 화면에 머티리얼 디자인 가이드라인 적용

- [ ] 스크립팅 관련 클래스 재작성

- [x] BasicHardKeyboard 구현

- [ ] BasicCharacterGenerator 구현

- [ ] 플릭, ALT키 등을 이용한 기호 입력 구현

**Comment by RanolP** [comment]
이벤트 처리 라이브러리로 유명한 것은 [Guava](https://github.com/google/guava)의 [EventBus](https://github.com/google/guava/wiki/EventBusExplained)를 fork해서 안드로이드 지원을 추가한 Square 사의 [Otto](https://github.com/square/otto) 가 유명하여 이를 추천하려 하였으나 Otto 의 [README.md](https://github.com/square/otto/blob/master/README.md) 를 살펴보면 다음과 같은 글이 적혀있습니다.

> This project is deprecated in favor of RxJava and RxAndroid. These projects permit the same event-driven programming model as Otto, but they’re more capable and offer better control of threading.

> (간략한 해석) Otto는 RxJava와 RxAndroid보다 나쁘므로 비권장됩니다. Rx는 Otto와 유사하게 이벤트 기반 프로그래밍 모델을 제공합니다. 그러나 Rx가 더 유용하고 스레딩에서 이점이 있습니다.

따라서 헌옷 프로젝트의 이벤트 라이브러리로 Rx를 추천하는 바이며, Rx 자체는 현재의 이벤트 코드를 훌륭히 대체할 수 있게 도와줍니다. 다만 이벤트 객체가 넘어왔을때 계속 instanceof를 사용해 객체를 확인하는 것은 난잡하고, 불필요한 코드입니다. 따라서 Rx를 기반으로 EventBus와 유사한 방식으로 코드를 작성하게 해주는 [RxBus](https://github.com/AndroidKnife/RxBus) 라이브러리 사용이 좋다고 생각합니다.
